vim.opt.conceallevel = 3
vim.opt.wrap = true
vim.keymap.set('n', '<C-Space>', '<Plug>(neorg.qol.todo-items.todo.task-cycle)', { buffer = true, desc = '[neorg] Cycle task status' })
vim.keymap.set('n', '<BS>', '<Plug>(neorg.esupports.hop.hop-link)', { buffer = true, desc = '[neorg] Open link under cursor' })
vim.keymap.set('n', '<leader>ojd', '<Plug>(neorg.tempus.insert-date)', { buffer = true, desc = '[neorg] Insert date link' })
vim.keymap.set('n', '<leader>ojt', '<cmd>Neorg journal today<cr>', { buffer = true, desc = "[neorg] Open today's note" })
vim.keymap.set('n', '<leader>oli', '<Plug>(neorg.pivot.list.invert)', { buffer = true, desc = '[neorg] Invert items on a list' })
vim.keymap.set('n', '<leader>olt', '<Plug>(neorg.pivot.list.toggle)', { buffer = true, desc = '[neorg] Toggle list ordering' })
vim.keymap.set('n', '<leader>oa', '<Plug>(neorg.qol.todo-items.todo.task-ambiguous)', { buffer = true, desc = '[neorg] Mark task as ambiguous' })
vim.keymap.set('n', '<leader>oc', '<Plug>(neorg.qol.todo-items.todo.task-cancelled)', { buffer = true, desc = '[neorg] Mark task as cancelled' })
vim.keymap.set('n', '<leader>od', '<Plug>(neorg.qol.todo-items.todo.task-done)', { buffer = true, desc = '[neorg] Mark task as done' })
vim.keymap.set('n', '<leader>oh', '<Plug>(neorg.qol.todo-items.todo.task-on-hold)', { buffer = true, desc = '[neorg] Mark task as on-hold' })
vim.keymap.set('n', '<leader>oi', '<Plug>(neorg.qol.todo-items.todo.task-important)', { buffer = true, desc = '[neorg] Mark task as important' })
vim.keymap.set('n', '<leader>op', '<Plug>(neorg.qol.todo-items.todo.task-pending)', { buffer = true, desc = '[neorg] Mark task as pending' })
vim.keymap.set('n', '<leader>or', '<Plug>(neorg.qol.todo-items.todo.task-recurring)', { buffer = true, desc = '[neorg] Mark task as recurring' })
vim.keymap.set('n', '<leader>ou', '<Plug>(neorg.qol.todo-items.todo.task-undone)', { buffer = true, desc = '[neorg] Mark task as undone' })
vim.keymap.set('n', '<M-BS>', '<Plug>(neorg.esupports.hop.hop-link.vsplit)', { buffer = true, desc = '[neorg] Vsplit link under cursor' })
